### ISSUE TITLE
Update and sign group contract

### ISSUE THREAD

**Issue by hencr33k** [PoturovicAnel/ClothingStore#3]

**Comment by hencr33k** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwjluNq5qs_gAhUPz6YKHb32CQQQjRx6BAgBEAU&url=%2Furl%3Fsa%3Di%26rct%3Dj%26q%3D%26esrc%3Ds%26source%3Dimages%26cd%3D%26cad%3Drja%26uact%3D8%26ved%3D2ahUKEwjluNq5qs_gAhUPz6YKHb32CQQQjRx6BAgBEAU%26url%3Dhttps%253A%252F%252Fgiphy.com%252Fgifs%252Fjust-do-it-24xRxrDCLxhT2%26psig%3DAOvVaw0Oh0pPbvaC_vhlfhTW0xx9%26ust%3D1550924584571362&psig=AOvVaw0Oh0pPbvaC_vhlfhTW0xx9&ust=1550924584571362

**Comment by PoturovicAnel** [comment]
Done

**Comment by hodhod212** [comment]
fint
